# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
branches:
  only:
    - master
os:
  - linux
matrix:
  include:
    - julia: 1.3
    - julia: 1.5
  allow_failures:
    - julia: nightly
notifications:
  email: false
after_success:
  - if [[ $TRAVIS_JULIA_VERSION = 1.3 ]]; then
      julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())';
      julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())';
    fi